jobs:
  include:
    - os: linux
      arch: amd64
      dist: focal
      script:
        - gcloud --version
      deploy:
        provider: gcs
        key_file: gcs-access.json
        bucket: gcp_vaishali_bucket
        edge:
          source: travis-ci/dpl
          branch: cs-fix-py
        on:
          all_branches: true
