jobs:
  include:
    - os: linux
      arch: amd64
      dist: focal
      script:
        - gcloud --version
      deploy:
        provider: gae
        key_file: gae-access.json
        on:
          all_branches: true
