jobs:
  include:
    - os: osx
      osx_image: xcode12.5
      script: true
      deploy:
        provider: gae
        keyfile: gae-access.json
        edge:
          source: travis-ci/dpl
          branch: cs-fix-py
        on:
          all_branches: true
