jobs:
  include:
    - os: linux
      arch: amd64
      dist: focal
      script:
        - gcloud --version
      deploy:
        provider: gae
        key-file: gae-access.json
        edge:
          source: travis-ci/dpl
          branch: cs-fix-py
        on:
          all_branches: true
